//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class base1Entities : DbContext
    {
        public base1Entities()
            : base("name=base1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public DbSet<ESTADO> ESTADO { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<FORMAPAGO> FORMAPAGO { get; set; }
        public DbSet<PRODUCTOS> PRODUCTOS { get; set; }
    }
}
