//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public DETALLE_FACTURA()
        {
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public int ID_DETALLE { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<int> ID_FACTURA { get; set; }
        public Nullable<decimal> PRECIO_TOTAL { get; set; }
        public Nullable<int> CANTIDAD_DETALLE { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual FACTURA FACTURA { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
