//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_FACTURA
    {
        public DETALLE_FACTURA()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public int ID_DETALLE { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<decimal> PRECIO_TOTAL { get; set; }
        public Nullable<decimal> PRECIO_PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD_DETALLE { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
