//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLESERVICIO
    {
        public int ID_DETALLESERVICIO { get; set; }
        public int ID_SERVICIO { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD_DETALLE { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
