//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int ID_FACTURA { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_DETALLE { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_FACTURA { get; set; }
        public Nullable<decimal> SUB_TOTAL { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> SUB_TOTAL_IVA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual DETALLE_FACTURA DETALLE_FACTURA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
    }
}
