//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public int ID_INVENTARIO { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<decimal> STOCK_INVENTARIO { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public Nullable<decimal> CANTIDAD_SALIDA { get; set; }
        public Nullable<decimal> CANTIDAD_INGRESO { get; set; }
        public Nullable<decimal> PRECIO_UNITARIO { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
