//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public PRODUCTOS()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
            this.INVENTARIO = new HashSet<INVENTARIO>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<int> ID_UNIDAD { get; set; }
        public string DESCRIPCION_PRODUCTO { get; set; }
    
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual ICollection<INVENTARIO> INVENTARIO { get; set; }
        public virtual UNIDADES UNIDADES { get; set; }
    }
}
