//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL
    {
        public ROL()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int ID_ESTADO { get; set; }
        public int ID_ROL { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
