//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDADES
    {
        public UNIDADES()
        {
            this.PRODUCTOS = new HashSet<PRODUCTOS>();
        }
    
        public int ID_UNIDAD { get; set; }
        public string DESCRIPCION_UNIDAD { get; set; }
        public string ABREVIATURA_UNIDAD { get; set; }
        public Nullable<decimal> EQUIVALENCIA_UNIDAD { get; set; }
    
        public virtual ICollection<PRODUCTOS> PRODUCTOS { get; set; }
    }
}
